### ISSUE TITLE
Update registration status

### ISSUE THREAD

**Issue by andrewbates09** [WSU-LUG/wsucon-static#11]
The registration bar needs to be updated.

See https://github.com/WSU-LUG/wsucon-static/tree/registration-update

**Comment by RachelMiri** [comment]
Done :)

**Comment by andrewbates09** [comment]
Not done.

See the original branch [registration-update](https://github.com/WSU-LUG/wsucon-static/tree/registration-update) and merge that and your registration branch together.

**Comment by RachelMiri** [comment]
done...
